export default {
      ezRed: '#f04e2f',
      ezBlue: '#4A90E2',
      ezOrange: '#f0922f',
      black: '#000000',
      lightBlack: '#222222',
      white: '#ffffff',
      gray: '#666',
      lightGray: '#999',
      backgroundGray: '#DDDDDD',
      statusOk: '#4A90E2',
      statusChanged: '#589742',
      statusCanceled: '#9B9B9B',
      statusNoShow: '#4A4A4A',
      // confirm-icon-normal: '#eee',
      // confirm-icon-hover: '#ccc',
      soLightGray: '#f7f7f7',
      hrGray: '#EAEAEA',
      hrBorderGray: '#CCCCCC',
      menuGray: '#F5F5F5',
}
